'use strict';

// Warrior talent trees for World of Warcraft: Forever ("Classic+").
//
// Source: forever-talents-notes.md, a beta screenshot transcribed and then
// corrected tooltip-by-tooltip with the repo owner (who has early/press
// access ahead of the public beta). See that file for exactly which numbers
// are [CONFIRMED] verbatim vs. an "assumed"/"presumed" linear extrapolation
// from a single confirmed rank. Nothing here has been cross-checked against
// a second independent source (none exists publicly yet as of 2026-09-13 --
// see forever-talents-notes.md's "Cross-checked against public sources").
//
// Every rank description is written the way in-game tooltips are: passive
// talents (nothing to cast, just an always-on effect or a modifier to some
// other ability) start with "Passive.", and every activated spell states
// its Rage cost and cooldown up front -- except Sweeping Strikes and Last
// Stand, which are genuinely free of a Rage cost in Classic (carried over
// unconfirmed for Forever), and Piercing Howl, whose Rage cost is not yet
// known at all (flagged inline below).
//
// PLACEHOLDER, PENDING REVIEW:
//  - Grid position (tier/col) is a best guess, not the real Forever layout:
//    talents unchanged from Classic keep their Classic tier/col, and moved
//    or brand-new talents are slotted into whatever gap that leaves nearby.
//    The repo owner is correcting this by hand, tree by tree, from an
//    in-game reference (Arms/Fury/Protection all corrected 2026-09-13).
//  - Icons are the real Classic icon where a talent's name/identity carried
//    over from Classic (even if its effect changed); brand-new talents use
//    `inv_misc_questionmark` (a real WoW "unknown" icon) as an explicit
//    placeholder rather than a guessed-and-possibly-wrong icon.
//  - spellId is omitted (null) for brand-new talents -- there's no Classic
//    spell to link to, and the Forever spell ID isn't known.
//  - A few prerequisite links are carried over unchanged from Classic
//    (adjusted only where a max-rank change would make the old requirement
//    impossible, e.g. Impale->Deep Wounds) and are not yet reconfirmed for
//    Forever specifically.
//  - Improved Slam is placed under Arms per the screenshot, but it's a Fury
//    talent in Classic and this move was never explicitly reconfirmed the
//    way Iron Will's and Improved Thunder Clap's tree moves were -- flagging
//    it as the one placement most likely to just be a transcription error.

const PLACEHOLDER_ICON = 'inv_misc_questionmark';

const TALENT_TREES = [
  {
    key: 'arms',
    name: 'Arms',
    icon: 'ability_rogue_eviscerate',
    talents: [
      { key: 'improved-heroic-strike', name: 'Improved Heroic Strike', tier: 1, col: 1, maxRank: 3, icon: 'ability_rogue_ambush', spellId: 12282, ranks: [
        'Passive. Reduces the cost of your Heroic Strike ability by 1 Rage.',
        'Passive. Reduces the cost of your Heroic Strike ability by 2 Rage.',
        'Passive. Reduces the cost of your Heroic Strike ability by 3 Rage.',
      ] },
      { key: 'deflection', name: 'Deflection', tier: 1, col: 2, maxRank: 5, icon: 'ability_parry', spellId: 16462, ranks: [
        'Passive. Increases your Parry chance by 1%.',
        'Passive. Increases your Parry chance by 2%.',
        'Passive. Increases your Parry chance by 3%.',
        'Passive. Increases your Parry chance by 4%.',
        'Passive. Increases your Parry chance by 5%.',
      ] },
      { key: 'improved-rend', name: 'Improved Rend', tier: 1, col: 3, maxRank: 3, icon: 'ability_gouge', spellId: 12286, ranks: [
        'Passive. Increases the Bleed damage done by your Rend ability by 12%.',
        'Passive. Increases the Bleed damage done by your Rend ability by 24%.',
        'Passive. Increases the Bleed damage done by your Rend ability by 36%.',
      ] },
      { key: 'improved-charge', name: 'Improved Charge', tier: 2, col: 1, maxRank: 2, icon: 'ability_warrior_charge', spellId: 12285, ranks: [
        'Passive. Increases the Rage generated by your Charge ability by 3.',
        'Passive. Increases the Rage generated by your Charge ability by 6.',
      ] },
      { key: 'improved-tactical-mastery', name: 'Improved Tactical Mastery', tier: 2, col: 2, maxRank: 5, icon: 'spell_nature_enchantarmor', spellId: 12295, ranks: [
        'Passive. Tactical Mastery lets you retain up to an additional 3 Rage when you change stances.',
        'Passive. Tactical Mastery lets you retain up to an additional 6 Rage when you change stances.',
        'Passive. Tactical Mastery lets you retain up to an additional 9 Rage when you change stances.',
        'Passive. Tactical Mastery lets you retain up to an additional 12 Rage when you change stances.',
        'Passive. Tactical Mastery lets you retain up to an additional 15 Rage when you change stances.',
      ] },
      { key: 'improved-overpower', name: 'Improved Overpower', tier: 2, col: 4, maxRank: 2, icon: 'inv_sword_05', spellId: 12290, ranks: [
        'Passive. Increases the critical strike chance of your Overpower ability by 25%.',
        'Passive. Increases the critical strike chance of your Overpower ability by 50%.',
      ] },
      { key: 'anger-management', name: 'Anger Management', tier: 3, col: 2, maxRank: 1, icon: 'spell_holy_blessingofstamina', spellId: 12296, requires: { key: 'improved-tactical-mastery', rank: 5 }, ranks: [
        'Passive. Generates 1 Rage every 3 sec while in combat, and reduces Rage loss while out of combat by 30%.',
      ] },
      { key: 'deep-wounds', name: 'Deep Wounds', tier: 3, col: 3, maxRank: 3, icon: 'ability_backstab', spellId: 12834, requires: { key: 'improved-rend', rank: 3 }, ranks: [
        "Passive. Your critical strikes cause your opponent to bleed, dealing 20% of your melee weapon's average damage over 12 sec.",
        "Passive. Your critical strikes cause your opponent to bleed, dealing 40% of your melee weapon's average damage over 12 sec.",
        "Passive. Your critical strikes cause your opponent to bleed, dealing 60% of your melee weapon's average damage over 12 sec.",
      ] },
      { key: 'spearing-strike', name: 'Spearing Strike', tier: 4, col: 1, maxRank: 1, icon: PLACEHOLDER_ICON, spellId: null, ranks: [
        '15 Rage, Melee Range, 10 sec cooldown, Instant. A brutal attack that deals 40% weapon damage. Deals an additional 80% weapon damage against Giants, Dragonkin, and mounted targets. Mounted targets are dismounted.',
      ] },
      { key: 'two-handed-weapon-specialization', name: 'Two-Handed Weapon Specialization', tier: 4, col: 2, maxRank: 3, icon: 'inv_axe_09', spellId: 12163, ranks: [
        'Passive. Increases the damage you deal with two-handed melee weapons by 1%.',
        'Passive. Increases the damage you deal with two-handed melee weapons by 2%.',
        'Passive. Increases the damage you deal with two-handed melee weapons by 3%.',
      ] },
      { key: 'impale', name: 'Impale', tier: 4, col: 3, maxRank: 2, icon: 'ability_searingarrow', spellId: 16493, ranks: [
        'Passive. Increases the critical strike damage bonus of your abilities by 10%.',
        'Passive. Increases the critical strike damage bonus of your abilities by 20%.',
      ] },
      { key: 'bloodthrill', name: 'Bloodthrill', tier: 5, col: 1, maxRank: 5, icon: PLACEHOLDER_ICON, spellId: null, ranks: [
        'Passive. Your melee attacks against targets afflicted by your Rend have a 2% chance to activate your Overpower ability for 1 attack on your current target. Lasts 6 seconds.',
        'Passive. Your melee attacks against targets afflicted by your Rend have a 4% chance to activate your Overpower ability for 1 attack on your current target. Lasts 6 seconds.',
        'Passive. Your melee attacks against targets afflicted by your Rend have a 6% chance to activate your Overpower ability for 1 attack on your current target. Lasts 6 seconds.',
        'Passive. Your melee attacks against targets afflicted by your Rend have a 8% chance to activate your Overpower ability for 1 attack on your current target. Lasts 6 seconds.',
        'Passive. Your melee attacks against targets afflicted by your Rend have a 10% chance to activate your Overpower ability for 1 attack on your current target. Lasts 6 seconds.',
      ] },
      { key: 'sweeping-strikes', name: 'Sweeping Strikes', tier: 5, col: 2, maxRank: 1, icon: 'ability_rogue_slicedice', spellId: 12292, ranks: [
        'Instant, 30 sec cooldown, Requires Battle Stance. Your next 5 melee attacks strike an additional nearby opponent.',
      ] },
      { key: 'weaponmaster', name: 'Weaponmaster', tier: 5, col: 3, maxRank: 5, icon: PLACEHOLDER_ICON, spellId: null, ranks: [
        "Passive. Gives your melee weapon attacks a benefit depending on the weapon: Axe/Polearm: +1% critical strike chance. Mace/Staff: attacks ignore 3% of your target's armor. Sword: 1% chance to trigger an extra attack on the target.",
        "Passive. Gives your melee weapon attacks a benefit depending on the weapon: Axe/Polearm: +2% critical strike chance. Mace/Staff: attacks ignore 6% of your target's armor. Sword: 2% chance to trigger an extra attack on the target.",
        "Passive. Gives your melee weapon attacks a benefit depending on the weapon: Axe/Polearm: +3% critical strike chance. Mace/Staff: attacks ignore 9% of your target's armor. Sword: 3% chance to trigger an extra attack on the target.",
        "Passive. Gives your melee weapon attacks a benefit depending on the weapon: Axe/Polearm: +4% critical strike chance. Mace/Staff: attacks ignore 12% of your target's armor. Sword: 4% chance to trigger an extra attack on the target.",
        "Passive. Gives your melee weapon attacks a benefit depending on the weapon: Axe/Polearm: +5% critical strike chance. Mace/Staff: attacks ignore 15% of your target's armor. Sword: 5% chance to trigger an extra attack on the target.",
      ] },
      { key: 'improved-slam', name: 'Improved Slam', tier: 6, col: 1, maxRank: 2, icon: 'ability_warrior_decisivestrike', spellId: 12862, ranks: [
        'Passive. Reduces the global cooldown and cast time of your Slam ability by 0.25 sec.',
        'Passive. Reduces the global cooldown and cast time of your Slam ability by 0.25 sec. In addition, Slam no longer interrupts your melee swing time.',
      ] },
      { key: 'improved-hamstring', name: 'Improved Hamstring', tier: 6, col: 3, maxRank: 3, icon: 'ability_shockwave', spellId: 12289, ranks: [
        'Passive. Gives your Hamstring ability a 5% chance to immobilize the target for 5 sec.',
        'Passive. Gives your Hamstring ability a 10% chance to immobilize the target for 5 sec.',
        'Passive. Gives your Hamstring ability a 15% chance to immobilize the target for 5 sec.',
      ] },
      { key: 'mortal-strike', name: 'Mortal Strike', tier: 7, col: 2, maxRank: 1, icon: 'ability_warrior_savageblow', spellId: 12294, requires: { key: 'sweeping-strikes', rank: 1 }, ranks: [
        '30 Rage, Instant, 6 sec cooldown, Melee Range. A vicious strike that deals weapon damage plus 85 and wounds the target, reducing the effectiveness of any healing by 50% for 10 sec.',
      ] },
    ],
  },
  {
    key: 'fury',
    name: 'Fury',
    icon: 'ability_warrior_innerrage',
    talents: [
      { key: 'booming-voice', name: 'Booming Voice', tier: 1, col: 2, maxRank: 5, icon: 'spell_nature_purge', spellId: 12321, ranks: [
        'Passive. Increases the radius of your Battle Shout and Demoralizing Shout abilities by 10%.',
        'Passive. Increases the radius of your Battle Shout and Demoralizing Shout abilities by 20%.',
        'Passive. Increases the radius of your Battle Shout and Demoralizing Shout abilities by 30%.',
        'Passive. Increases the radius of your Battle Shout and Demoralizing Shout abilities by 40%.',
        'Passive. Increases the radius of your Battle Shout and Demoralizing Shout abilities by 50%.',
      ] },
      { key: 'cruelty', name: 'Cruelty', tier: 1, col: 3, maxRank: 5, icon: 'ability_rogue_eviscerate', spellId: 12320, ranks: [
        'Passive. Increases your chance to get a critical strike with melee attacks by 1%.',
        'Passive. Increases your chance to get a critical strike with melee attacks by 2%.',
        'Passive. Increases your chance to get a critical strike with melee attacks by 3%.',
        'Passive. Increases your chance to get a critical strike with melee attacks by 4%.',
        'Passive. Increases your chance to get a critical strike with melee attacks by 5%.',
      ] },
      { key: 'iron-will', name: 'Iron Will', tier: 2, col: 2, maxRank: 5, icon: 'spell_magic_magearmor', spellId: 12300, ranks: [
        'Passive. Reduces the duration of Stun and Fear effects inflicted on you by 3%.',
        'Passive. Reduces the duration of Stun and Fear effects inflicted on you by 6%.',
        'Passive. Reduces the duration of Stun and Fear effects inflicted on you by 9%.',
        'Passive. Reduces the duration of Stun and Fear effects inflicted on you by 12%.',
        'Passive. Reduces the duration of Stun and Fear effects inflicted on you by 15%.',
      ] },
      { key: 'unbridled-wrath', name: 'Unbridled Wrath', tier: 2, col: 3, maxRank: 5, icon: 'spell_nature_stoneclawtotem', spellId: 12322, ranks: [
        'Passive. Gives you a 12% chance to generate 1 additional Rage (2 for two-handed weapons) when you deal melee damage with a weapon.',
        'Passive. Gives you a 24% chance to generate 1 additional Rage (2 for two-handed weapons) when you deal melee damage with a weapon.',
        'Passive. Gives you a 36% chance to generate 1 additional Rage (2 for two-handed weapons) when you deal melee damage with a weapon.',
        'Passive. Gives you a 48% chance to generate 1 additional Rage (2 for two-handed weapons) when you deal melee damage with a weapon.',
        'Passive. Gives you a 60% chance to generate 1 additional Rage (2 for two-handed weapons) when you deal melee damage with a weapon.',
      ] },
      { key: 'improved-cleave', name: 'Improved Cleave', tier: 3, col: 1, maxRank: 3, icon: 'ability_warrior_cleave', spellId: 12329, ranks: [
        'Passive. Reduces the Rage cost of your Cleave ability by 1.',
        'Passive. Reduces the Rage cost of your Cleave ability by 2.',
        'Passive. Reduces the Rage cost of your Cleave ability by 3.',
      ] },
      // TODO: Rage cost not known -- the screenshot this was transcribed
      // from didn't show one, unlike every other activated spell here.
      // Confirm before relying on this for any rage-budget math.
      { key: 'piercing-howl', name: 'Piercing Howl', tier: 3, col: 2, maxRank: 1, icon: 'spell_shadow_deathscream', spellId: 12323, ranks: [
        'Instant, 10 sec cooldown. Causes all nearby enemies to be Dazed, reducing movement speed by 50% for 6 sec.',
      ] },
      { key: 'blood-craze', name: 'Blood Craze', tier: 3, col: 3, maxRank: 3, icon: 'spell_shadow_summonimp', spellId: 16487, ranks: [
        'Passive. Regenerates 1% of your total Health over 6 sec after being the victim of a critical strike, dealing damage with Bloodthirst, or suffering more than 20% of your maximum health from a single attack.',
        'Passive. Regenerates 2% of your total Health over 6 sec after being the victim of a critical strike, dealing damage with Bloodthirst, or suffering more than 20% of your maximum health from a single attack.',
        'Passive. Regenerates 3% of your total Health over 6 sec after being the victim of a critical strike, dealing damage with Bloodthirst, or suffering more than 20% of your maximum health from a single attack.',
      ] },
      { key: 'boundless-rage', name: 'Boundless Rage', tier: 3, col: 4, maxRank: 3, icon: PLACEHOLDER_ICON, spellId: null, ranks: [
        'Passive. Increases your maximum Rage by 10.',
        'Passive. Increases your maximum Rage by 20.',
        'Passive. Increases your maximum Rage by 30.',
      ] },
      { key: 'dual-wield-specialization', name: 'Dual Wield Specialization', tier: 4, col: 1, maxRank: 5, icon: 'ability_dualwield', spellId: 23584, ranks: [
        'Passive. Increases your off-hand weapon damage by 5%, off-hand Rage generation by 20%, and chance to hit with off-hand attacks by 2%.',
        'Passive. Increases your off-hand weapon damage by 10%, off-hand Rage generation by 40%, and chance to hit with off-hand attacks by 4%.',
        'Passive. Increases your off-hand weapon damage by 15%, off-hand Rage generation by 60%, and chance to hit with off-hand attacks by 6%.',
        'Passive. Increases your off-hand weapon damage by 20%, off-hand Rage generation by 80%, and chance to hit with off-hand attacks by 8%.',
        'Passive. Increases your off-hand weapon damage by 25%, off-hand Rage generation by 100%, and chance to hit with off-hand attacks by 10%.',
      ] },
      { key: 'raging-blows', name: 'Raging Blows', tier: 4, col: 2, maxRank: 1, icon: PLACEHOLDER_ICON, spellId: null, ranks: [
        'Passive. Causes your Whirlwind to also strike with your off-hand weapon, and reduces the Rage cost of your Cleave ability by 2.',
      ] },
      { key: 'enrage', name: 'Enrage', tier: 4, col: 3, maxRank: 5, icon: 'spell_shadow_unholyfrenzy', spellId: 12317, ranks: [
        'Passive. Gives you a 5% melee damage bonus for 12 sec up to a maximum of 12 swings after being the victim of a critical strike.',
        'Passive. Gives you a 10% melee damage bonus for 12 sec up to a maximum of 12 swings after being the victim of a critical strike.',
        'Passive. Gives you a 15% melee damage bonus for 12 sec up to a maximum of 12 swings after being the victim of a critical strike.',
        'Passive. Gives you a 20% melee damage bonus for 12 sec up to a maximum of 12 swings after being the victim of a critical strike.',
        'Passive. Gives you a 25% melee damage bonus for 12 sec up to a maximum of 12 swings after being the victim of a critical strike.',
      ] },
      { key: 'improved-execute', name: 'Improved Execute', tier: 4, col: 4, maxRank: 2, icon: 'inv_sword_48', spellId: 20502, ranks: [
        'Passive. Reduces the Rage cost of your Execute ability by 3.',
        'Passive. Reduces the Rage cost of your Execute ability by 5.',
      ] },
      { key: 'precision', name: 'Precision', tier: 5, col: 1, maxRank: 3, icon: PLACEHOLDER_ICON, spellId: null, ranks: [
        'Passive. Increases your chance to hit with all abilities and melee attacks by 1%.',
        'Passive. Increases your chance to hit with all abilities and melee attacks by 2%.',
        'Passive. Increases your chance to hit with all abilities and melee attacks by 3%.',
      ] },
      { key: 'death-wish', name: 'Death Wish', tier: 5, col: 2, maxRank: 1, icon: 'spell_shadow_deathpact', spellId: 12328, ranks: [
        '30 Rage, 3 min cooldown, Instant. When activated, increases Physical damage done by 20% and makes you immune to Fear effects, but increases all damage taken by 5%. Lasts 30 sec.',
      ] },
      { key: 'improved-intercept', name: 'Improved Intercept', tier: 5, col: 4, maxRank: 2, icon: 'ability_rogue_sprint', spellId: 20504, ranks: [
        'Passive. Reduces the cooldown of your Intercept ability by 5 sec.',
        'Passive. Reduces the cooldown of your Intercept ability by 10 sec.',
      ] },
      { key: 'improved-berserker-rage', name: 'Improved Berserker Rage', tier: 6, col: 1, maxRank: 2, icon: 'spell_nature_ancestralguardian', spellId: 20500, ranks: [
        'Passive. Your Berserker Rage ability will instantly generate 5 Rage and has a 50% chance to remove all movement-impairing effects when activated.',
        'Passive. Your Berserker Rage ability will instantly generate 10 Rage and has a 100% chance to remove all movement-impairing effects when activated.',
      ] },
      { key: 'flurry', name: 'Flurry', tier: 6, col: 3, maxRank: 5, icon: 'ability_ghoulfrenzy', spellId: 12319, requires: { key: 'enrage', rank: 5 }, ranks: [
        'Passive. Increases your attack speed by 5% for your next 3 swings after dealing a melee critical strike.',
        'Passive. Increases your attack speed by 10% for your next 3 swings after dealing a melee critical strike.',
        'Passive. Increases your attack speed by 15% for your next 3 swings after dealing a melee critical strike.',
        'Passive. Increases your attack speed by 20% for your next 3 swings after dealing a melee critical strike.',
        'Passive. Increases your attack speed by 25% for your next 3 swings after dealing a melee critical strike.',
      ] },
      { key: 'bloodthirst', name: 'Bloodthirst', tier: 7, col: 2, maxRank: 1, icon: 'spell_nature_bloodlust', spellId: 23881, requires: { key: 'death-wish', rank: 1 }, ranks: [
        '30 Rage, Instant, 6 sec cooldown, Melee Range. Instantly attack the target causing damage equal to 35% of your Attack Power plus 30, and increasing your movement speed by 10% for 10 sec.',
      ] },
    ],
  },
  {
    key: 'protection',
    name: 'Protection',
    icon: 'inv_shield_06',
    talents: [
      { key: 'shield-specialization', name: 'Shield Specialization', tier: 1, col: 2, maxRank: 5, icon: 'inv_shield_06', spellId: 12298, ranks: [
        'Passive. Increases your chance to Block attacks with a shield by 1% and grants you a 20% chance to generate 5 Rage when you Block.',
        'Passive. Increases your chance to Block attacks with a shield by 2% and grants you a 40% chance to generate 5 Rage when you Block.',
        'Passive. Increases your chance to Block attacks with a shield by 3% and grants you a 60% chance to generate 5 Rage when you Block.',
        'Passive. Increases your chance to Block attacks with a shield by 4% and grants you a 80% chance to generate 5 Rage when you Block.',
        'Passive. Increases your chance to Block attacks with a shield by 5% and grants you a 100% chance to generate 5 Rage when you Block.',
      ] },
      { key: 'anticipation', name: 'Anticipation', tier: 1, col: 3, maxRank: 5, icon: 'spell_nature_mirrorimage', spellId: 12297, ranks: [
        'Passive. Increases your Defense skill by 4.',
        'Passive. Increases your Defense skill by 8.',
        'Passive. Increases your Defense skill by 12.',
        'Passive. Increases your Defense skill by 16.',
        'Passive. Increases your Defense skill by 20.',
      ] },
      { key: 'improved-bloodrage', name: 'Improved Bloodrage', tier: 2, col: 1, maxRank: 2, icon: 'ability_racial_bloodrage', spellId: 12301, ranks: [
        'Passive. Increases the Rage generated by your Bloodrage ability by 25%.',
        'Passive. Increases the Rage generated by your Bloodrage ability by 50%.',
      ] },
      { key: 'toughness', name: 'Toughness', tier: 2, col: 3, maxRank: 5, icon: 'spell_holy_devotion', spellId: 12299, ranks: [
        'Passive. Increases your Armor value from items by 2%.',
        'Passive. Increases your Armor value from items by 4%.',
        'Passive. Increases your Armor value from items by 6%.',
        'Passive. Increases your Armor value from items by 8%.',
        'Passive. Increases your Armor value from items by 10%.',
      ] },
      { key: 'improved-thunder-clap', name: 'Improved Thunder Clap', tier: 2, col: 4, maxRank: 3, icon: 'ability_thunderclap', spellId: 12287, ranks: [
        'Passive. Reduces the cost of your Thunder Clap ability by 2 Rage.',
        'Passive. Reduces the cost of your Thunder Clap ability by 4 Rage.',
        'Passive. Reduces the cost of your Thunder Clap ability by 6 Rage.',
      ] },
      { key: 'last-stand', name: 'Last Stand', tier: 3, col: 1, maxRank: 1, icon: 'spell_holy_ashestoashes', spellId: 12975, requires: { key: 'improved-bloodrage', rank: 2 }, ranks: [
        'Instant, 3 min cooldown. When activated, this ability temporarily grants you an additional 30% of your maximum Health for 20 sec. When the effect ends, the health is lost.',
      ] },
      { key: 'improved-revenge', name: 'Improved Revenge', tier: 3, col: 3, maxRank: 3, icon: 'ability_warrior_revenge', spellId: 12797, ranks: [
        'Passive. Increases damage dealt by your Revenge ability by 20%.',
        'Passive. Increases damage dealt by your Revenge ability by 40%.',
        'Passive. Increases damage dealt by your Revenge ability by 60%.',
      ] },
      { key: 'defiance', name: 'Defiance', tier: 3, col: 4, maxRank: 3, icon: 'ability_warrior_innerrage', spellId: 12303, ranks: [
        'Passive. Increases all threat generated in Defensive Stance by an additional 5% while a shield is equipped.',
        'Passive. Increases all threat generated in Defensive Stance by an additional 10% while a shield is equipped.',
        'Passive. Increases all threat generated in Defensive Stance by an additional 15% while a shield is equipped.',
      ] },
      { key: 'improved-sunder-armor', name: 'Improved Sunder Armor', tier: 4, col: 1, maxRank: 3, icon: 'ability_warrior_sunder', spellId: 12308, ranks: [
        'Passive. Reduces the cost of your Sunder Armor ability by 1 Rage.',
        'Passive. Reduces the cost of your Sunder Armor ability by 2 Rage.',
        'Passive. Reduces the cost of your Sunder Armor ability by 3 Rage.',
      ] },
      { key: 'improved-disarm', name: 'Improved Disarm', tier: 4, col: 2, maxRank: 3, icon: 'ability_warrior_disarm', spellId: 12313, ranks: [
        'Passive. Reduces the cooldown of your Disarm ability by 7 sec.',
        'Passive. Reduces the cooldown of your Disarm ability by 14 sec.',
        'Passive. Reduces the cooldown of your Disarm ability by 21 sec.',
      ] },
      { key: 'improved-shield-wall', name: 'Improved Shield Wall', tier: 5, col: 1, maxRank: 2, icon: 'ability_warrior_shieldwall', spellId: 12312, ranks: [
        'Passive. Reduces the cooldown of your Shield Wall ability by 5.5 min.',
        'Passive. Reduces the cooldown of your Shield Wall ability by 11 min.',
      ] },
      { key: 'concussion-blow', name: 'Concussion Blow', tier: 5, col: 2, maxRank: 1, icon: 'ability_thunderbolt', spellId: 12809, ranks: [
        '10 Rage, Melee Range, 45 sec cooldown, Instant. Stuns the target for 5 sec.',
      ] },
      { key: 'improved-shield-bash', name: 'Improved Shield Bash', tier: 5, col: 3, maxRank: 2, icon: 'ability_warrior_shieldbash', spellId: 12311, ranks: [
        'Passive. Gives your Shield Bash ability a 50% chance to Silence the target for 3 sec.',
        'Passive. Gives your Shield Bash ability a 100% chance to Silence the target for 3 sec.',
      ] },
      { key: 'shield-slam', name: 'Shield Slam', tier: 7, col: 2, maxRank: 1, icon: 'inv_shield_05', spellId: 23922, requires: { key: 'concussion-blow', rank: 1 }, ranks: [
        '30 Rage, Melee Range, 6 sec cooldown, Instant. Slams the target with your shield, causing 421 to 439 damage, increased by your Block Value, and has a 50% chance of dispelling 1 magic effect on the target. Causes a very high amount of threat.',
      ] },
      { key: 'master-of-defense', name: 'Master of Defense', tier: 3, col: 2, maxRank: 2, icon: PLACEHOLDER_ICON, spellId: null, requires: { key: 'shield-specialization', rank: 5 }, ranks: [
        'Passive. Grants you a 50% chance to generate 5 Rage when you Dodge or Parry while a shield is equipped.',
        'Passive. Grants you a 100% chance to generate 10 Rage when you Dodge or Parry while a shield is equipped.',
      ] },
      { key: 'vanguard', name: 'Vanguard', tier: 4, col: 3, maxRank: 1, icon: PLACEHOLDER_ICON, spellId: null, ranks: [
        'Passive. Your Charge ability is now usable while in Defensive Stance.',
      ] },
      { key: 'vitality', name: 'Vitality', tier: 5, col: 4, maxRank: 5, icon: PLACEHOLDER_ICON, spellId: null, ranks: [
        'Passive. Increases your Stamina and Strength by 2%.',
        'Passive. Increases your Stamina and Strength by 4%.',
        'Passive. Increases your Stamina and Strength by 6%.',
        'Passive. Increases your Stamina and Strength by 8%.',
        'Passive. Increases your Stamina and Strength by 10%.',
      ] },
      { key: 'focused-rage', name: 'Focused Rage', tier: 6, col: 1, maxRank: 3, icon: PLACEHOLDER_ICON, spellId: null, ranks: [
        'Passive. Reduces the Rage cost of your defensive abilities by 1.',
        'Passive. Reduces the Rage cost of your defensive abilities by 2.',
        'Passive. Reduces the Rage cost of your defensive abilities by 3.',
      ] },
      { key: 'bastion', name: 'Bastion', tier: 6, col: 3, maxRank: 5, icon: PLACEHOLDER_ICON, spellId: null, ranks: [
        'Passive. Reduces all damage you take by 2% while a shield is equipped.',
        'Passive. Reduces all damage you take by 4% while a shield is equipped.',
        'Passive. Reduces all damage you take by 6% while a shield is equipped.',
        'Passive. Reduces all damage you take by 8% while a shield is equipped.',
        'Passive. Reduces all damage you take by 10% while a shield is equipped.',
      ] },
    ],
  },
];

// Unconfirmed for Forever -- carried over from Classic as a starting
// placeholder. See "Remaining open questions" in forever-talents-notes.md.
const TALENT_MAX_POINTS = 51;
const TALENT_POINTS_PER_TIER = 5;
