'use strict';

// Classic (vanilla, pre-Cataclysm / "Classic Era") Warrior talent trees.
//
// Sourced and cross-referenced live from two independent sites so both the
// numbers and the grid layout/icons/prerequisites are verified against each
// other, not from memory:
//  - Rank-by-rank tooltip text: zockify.com's Classic Era/Anniversary/
//    Hardcore talent calculator data file.
//  - Grid position (tier/col), max rank, real spell ID, icon and
//    prerequisite text: Wowhead's live talent calculator DOM
//    (wow.zamimg.com icons, wowhead.com/classic/spell=<id>/<slug> links).
//
// tier is 1-indexed (row 1 = top row of a tree). col is 1-indexed, 1-4.
// requires (when present) is {key, rank}: the prerequisite talent's key and
// the minimum rank needed in it, in addition to the standard rule that tier
// N needs 5*(N-1) points already spent somewhere in that same tree.

const TALENT_TREES = [
  {
    key: 'arms',
    name: 'Arms',
    icon: 'ability_rogue_eviscerate',
    talents: [
      { key: 'improved-heroic-strike', name: 'Improved Heroic Strike', tier: 1, col: 1, maxRank: 3, icon: 'ability_rogue_ambush', spellId: 12282, ranks: [
        'Reduces the cost of your Heroic Strike ability by 1 rage point.',
        'Reduces the cost of your Heroic Strike ability by 2 rage points.',
        'Reduces the cost of your Heroic Strike ability by 3 rage points.',
      ] },
      { key: 'deflection', name: 'Deflection', tier: 1, col: 2, maxRank: 5, icon: 'ability_parry', spellId: 16462, ranks: [
        'Increases your Parry chance by 1%.',
        'Increases your Parry chance by 2%.',
        'Increases your Parry chance by 3%.',
        'Increases your Parry chance by 4%.',
        'Increases your Parry chance by 5%.',
      ] },
      { key: 'improved-rend', name: 'Improved Rend', tier: 1, col: 3, maxRank: 3, icon: 'ability_gouge', spellId: 12286, ranks: [
        "Increases the bleed damage done by your Rend ability by 15%.",
        "Increases the bleed damage done by your Rend ability by 25%.",
        "Increases the bleed damage done by your Rend ability by 35%.",
      ] },
      { key: 'improved-charge', name: 'Improved Charge', tier: 2, col: 1, maxRank: 2, icon: 'ability_warrior_charge', spellId: 12285, ranks: [
        'Increases the amount of rage generated by your Charge ability by 3.',
        'Increases the amount of rage generated by your Charge ability by 6.',
      ] },
      { key: 'tactical-mastery', name: 'Tactical Mastery', tier: 2, col: 2, maxRank: 5, icon: 'spell_nature_enchantarmor', spellId: 12295, ranks: [
        'You retain up to 5 of your rage points when you change stances.',
        'You retain up to 10 of your rage points when you change stances.',
        'You retain up to 15 of your rage points when you change stances.',
        'You retain up to 20 of your rage points when you change stances.',
        'You retain up to 25 of your rage points when you change stances.',
      ] },
      { key: 'improved-thunder-clap', name: 'Improved Thunder Clap', tier: 2, col: 4, maxRank: 3, icon: 'ability_thunderclap', spellId: 12287, ranks: [
        'Reduces the cost of your Thunder Clap ability by 1 rage point.',
        'Reduces the cost of your Thunder Clap ability by 2 rage points.',
        'Reduces the cost of your Thunder Clap ability by 4 rage points.',
      ] },
      { key: 'improved-overpower', name: 'Improved Overpower', tier: 3, col: 1, maxRank: 2, icon: 'inv_sword_05', spellId: 12290, ranks: [
        'Increases the critical strike chance of your Overpower ability by 25%.',
        'Increases the critical strike chance of your Overpower ability by 50%.',
      ] },
      { key: 'anger-management', name: 'Anger Management', tier: 3, col: 2, maxRank: 1, icon: 'spell_holy_blessingofstamina', spellId: 12296, requires: { key: 'tactical-mastery', rank: 5 }, ranks: [
        'Increases the time required for your rage to decay while out of combat by 30%.',
      ] },
      { key: 'deep-wounds', name: 'Deep Wounds', tier: 3, col: 3, maxRank: 3, icon: 'ability_backstab', spellId: 12834, requires: { key: 'improved-rend', rank: 3 }, ranks: [
        "Your critical strikes cause the opponent to bleed, dealing 20% of your melee weapon's average damage over 12 sec.",
        "Your critical strikes cause the opponent to bleed, dealing 40% of your melee weapon's average damage over 12 sec.",
        "Your critical strikes cause the opponent to bleed, dealing 60% of your melee weapon's average damage over 12 sec.",
      ] },
      { key: 'two-handed-weapon-specialization', name: 'Two-Handed Weapon Specialization', tier: 4, col: 2, maxRank: 5, icon: 'inv_axe_09', spellId: 12163, ranks: [
        'Increases the damage you deal with two-handed melee weapons by 1%.',
        'Increases the damage you deal with two-handed melee weapons by 2%.',
        'Increases the damage you deal with two-handed melee weapons by 3%.',
        'Increases the damage you deal with two-handed melee weapons by 4%.',
        'Increases the damage you deal with two-handed melee weapons by 5%.',
      ] },
      { key: 'impale', name: 'Impale', tier: 4, col: 3, maxRank: 2, icon: 'ability_searingarrow', spellId: 16493, requires: { key: 'deep-wounds', rank: 3 }, ranks: [
        'Increases the critical strike damage bonus of your abilities in Battle, Defensive, and Berserker stance by 10%.',
        'Increases the critical strike damage bonus of your abilities in Battle, Defensive, and Berserker stance by 20%.',
      ] },
      { key: 'axe-specialization', name: 'Axe Specialization', tier: 5, col: 1, maxRank: 5, icon: 'inv_axe_06', spellId: 12700, ranks: [
        'Increases your chance to get a critical strike with Axes by 1%.',
        'Increases your chance to get a critical strike with Axes by 2%.',
        'Increases your chance to get a critical strike with Axes by 3%.',
        'Increases your chance to get a critical strike with Axes by 4%.',
        'Increases your chance to get a critical strike with Axes by 5%.',
      ] },
      { key: 'sweeping-strikes', name: 'Sweeping Strikes', tier: 5, col: 2, maxRank: 1, icon: 'ability_rogue_slicedice', spellId: 12292, ranks: [
        'Your next 5 melee attacks strike an additional nearby opponent.',
      ] },
      { key: 'mace-specialization', name: 'Mace Specialization', tier: 5, col: 3, maxRank: 5, icon: 'inv_mace_01', spellId: 12284, ranks: [
        'Gives you a 1% chance to stun your target for 3 sec with a Mace.',
        'Gives you a 2% chance to stun your target for 3 sec with a Mace.',
        'Gives you a 3% chance to stun your target for 3 sec with a Mace.',
        'Gives you a 4% chance to stun your target for 3 sec with a Mace.',
        'Gives you a 6% chance to stun your target for 3 sec with a Mace.',
      ] },
      { key: 'sword-specialization', name: 'Sword Specialization', tier: 5, col: 4, maxRank: 5, icon: 'inv_sword_27', spellId: 12281, ranks: [
        'Gives you a 1% chance to get an extra attack on the same target after dealing damage with your Sword.',
        'Gives you a 2% chance to get an extra attack on the same target after dealing damage with your Sword.',
        'Gives you a 3% chance to get an extra attack on the same target after dealing damage with your Sword.',
        'Gives you a 4% chance to get an extra attack on the same target after dealing damage with your Sword.',
        'Gives you a 5% chance to get an extra attack on the same target after dealing damage with your Sword.',
      ] },
      { key: 'polearm-specialization', name: 'Polearm Specialization', tier: 6, col: 1, maxRank: 5, icon: 'inv_weapon_halbard_01', spellId: 12165, ranks: [
        'Increases your chance to get a critical strike with Polearms by 1%.',
        'Increases your chance to get a critical strike with Polearms by 2%.',
        'Increases your chance to get a critical strike with Polearms by 3%.',
        'Increases your chance to get a critical strike with Polearms by 4%.',
        'Increases your chance to get a critical strike with Polearms by 5%.',
      ] },
      { key: 'improved-hamstring', name: 'Improved Hamstring', tier: 6, col: 3, maxRank: 3, icon: 'ability_shockwave', spellId: 12289, ranks: [
        'Gives your Hamstring ability a 5% chance to immobilize the target for 5 sec.',
        'Gives your Hamstring ability a 10% chance to immobilize the target for 5 sec.',
        'Gives your Hamstring ability a 15% chance to immobilize the target for 5 sec.',
      ] },
      { key: 'mortal-strike', name: 'Mortal Strike', tier: 7, col: 2, maxRank: 1, icon: 'ability_warrior_savageblow', spellId: 12294, requires: { key: 'sweeping-strikes', rank: 1 }, ranks: [
        'A vicious strike that deals weapon damage plus 85 and wounds the target, reducing the effectiveness of any healing by 50% for 10 sec.',
      ] },
    ],
  },
  {
    key: 'fury',
    name: 'Fury',
    icon: 'ability_warrior_innerrage',
    talents: [
      { key: 'booming-voice', name: 'Booming Voice', tier: 1, col: 2, maxRank: 5, icon: 'spell_nature_purge', spellId: 12321, ranks: [
        'Increases the area of effect and duration of your Battle Shout and Demoralizing Shout by 10%.',
        'Increases the area of effect and duration of your Battle Shout and Demoralizing Shout by 20%.',
        'Increases the area of effect and duration of your Battle Shout and Demoralizing Shout by 30%.',
        'Increases the area of effect and duration of your Battle Shout and Demoralizing Shout by 40%.',
        'Increases the area of effect and duration of your Battle Shout and Demoralizing Shout by 50%.',
      ] },
      { key: 'cruelty', name: 'Cruelty', tier: 1, col: 3, maxRank: 5, icon: 'ability_rogue_eviscerate', spellId: 12320, ranks: [
        'Increases your chance to get a critical strike with melee weapons by 1%.',
        'Increases your chance to get a critical strike with melee weapons by 2%.',
        'Increases your chance to get a critical strike with melee weapons by 3%.',
        'Increases your chance to get a critical strike with melee weapons by 4%.',
        'Increases your chance to get a critical strike with melee weapons by 5%.',
      ] },
      { key: 'improved-demoralizing-shout', name: 'Improved Demoralizing Shout', tier: 2, col: 2, maxRank: 5, icon: 'ability_warrior_warcry', spellId: 12324, ranks: [
        "Increases the melee attack power reduction of your Demoralizing Shout by 8%.",
        "Increases the melee attack power reduction of your Demoralizing Shout by 16%.",
        "Increases the melee attack power reduction of your Demoralizing Shout by 24%.",
        "Increases the melee attack power reduction of your Demoralizing Shout by 32%.",
        "Increases the melee attack power reduction of your Demoralizing Shout by 40%.",
      ] },
      { key: 'unbridled-wrath', name: 'Unbridled Wrath', tier: 2, col: 3, maxRank: 5, icon: 'spell_nature_stoneclawtotem', spellId: 12322, ranks: [
        'Gives you a 8% chance to generate an additional Rage point when you deal melee damage with a weapon.',
        'Gives you a 16% chance to generate an additional Rage point when you deal melee damage with a weapon.',
        'Gives you a 24% chance to generate an additional Rage point when you deal melee damage with a weapon.',
        'Gives you a 32% chance to generate an additional Rage point when you deal melee damage with a weapon.',
        'Gives you a 40% chance to generate an additional Rage point when you deal melee damage with a weapon.',
      ] },
      { key: 'improved-cleave', name: 'Improved Cleave', tier: 3, col: 1, maxRank: 3, icon: 'ability_warrior_cleave', spellId: 12329, ranks: [
        'Increases the bonus damage done by your Cleave ability by 40%.',
        'Increases the bonus damage done by your Cleave ability by 80%.',
        'Increases the bonus damage done by your Cleave ability by 120%.',
      ] },
      { key: 'piercing-howl', name: 'Piercing Howl', tier: 3, col: 2, maxRank: 1, icon: 'spell_shadow_deathscream', spellId: 12323, ranks: [
        'Causes all enemies near the warrior to be dazed, reducing movement speed by 50% for 6 sec.',
      ] },
      { key: 'blood-craze', name: 'Blood Craze', tier: 3, col: 3, maxRank: 3, icon: 'spell_shadow_summonimp', spellId: 16487, ranks: [
        'Regenerates 1% of your total Health over 6 sec after being the victim of a critical strike.',
        'Regenerates 2% of your total Health over 6 sec after being the victim of a critical strike.',
        'Regenerates 3% of your total Health over 6 sec after being the victim of a critical strike.',
      ] },
      { key: 'improved-battle-shout', name: 'Improved Battle Shout', tier: 3, col: 4, maxRank: 5, icon: 'ability_warrior_battleshout', spellId: 12318, ranks: [
        'Increases the melee attack power bonus of your Battle Shout by 5%.',
        'Increases the melee attack power bonus of your Battle Shout by 10%.',
        'Increases the melee attack power bonus of your Battle Shout by 15%.',
        'Increases the melee attack power bonus of your Battle Shout by 20%.',
        'Increases the melee attack power bonus of your Battle Shout by 25%.',
      ] },
      { key: 'dual-wield-specialization', name: 'Dual Wield Specialization', tier: 4, col: 1, maxRank: 5, icon: 'ability_dualwield', spellId: 23584, ranks: [
        'Increases the damage done by your offhand weapon by 5%.',
        'Increases the damage done by your offhand weapon by 10%.',
        'Increases the damage done by your offhand weapon by 15%.',
        'Increases the damage done by your offhand weapon by 20%.',
        'Increases the damage done by your offhand weapon by 25%.',
      ] },
      { key: 'improved-execute', name: 'Improved Execute', tier: 4, col: 2, maxRank: 2, icon: 'inv_sword_48', spellId: 20502, ranks: [
        'Reduces the Rage cost of your Execute ability by 2.',
        'Reduces the Rage cost of your Execute ability by 5.',
      ] },
      { key: 'enrage', name: 'Enrage', tier: 4, col: 3, maxRank: 5, icon: 'spell_shadow_unholyfrenzy', spellId: 12317, ranks: [
        'Gives you a 5% melee damage bonus for 12 sec up to a maximum of 12 swings after being the victim of a critical strike.',
        'Gives you a 10% melee damage bonus for 12 sec up to a maximum of 12 swings after being the victim of a critical strike.',
        'Gives you a 15% melee damage bonus for 12 sec up to a maximum of 12 swings after being the victim of a critical strike.',
        'Gives you a 20% melee damage bonus for 12 sec up to a maximum of 12 swings after being the victim of a critical strike.',
        'Gives you a 25% melee damage bonus for 12 sec up to a maximum of 12 swings after being the victim of a critical strike.',
      ] },
      { key: 'improved-slam', name: 'Improved Slam', tier: 5, col: 1, maxRank: 5, icon: 'ability_warrior_decisivestrike', spellId: 12862, ranks: [
        'Decreases the casting time of your Slam ability by 0.1 sec.',
        'Decreases the casting time of your Slam ability by 0.2 sec.',
        'Decreases the casting time of your Slam ability by 0.3 sec.',
        'Decreases the casting time of your Slam ability by 0.4 sec.',
        'Decreases the casting time of your Slam ability by 0.5 sec.',
      ] },
      { key: 'death-wish', name: 'Death Wish', tier: 5, col: 2, maxRank: 1, icon: 'spell_shadow_deathpact', spellId: 12328, ranks: [
        'When activated, increases your physical damage by 20% and makes you immune to Fear effects, but lowers your armor and all resistances by 20%.  Lasts 30 sec.',
      ] },
      { key: 'improved-intercept', name: 'Improved Intercept', tier: 5, col: 4, maxRank: 2, icon: 'ability_rogue_sprint', spellId: 20504, ranks: [
        'Reduces the cooldown of your Intercept ability by 5 sec.',
        'Reduces the cooldown of your Intercept ability by 10 sec.',
      ] },
      { key: 'improved-berserker-rage', name: 'Improved Berserker Rage', tier: 6, col: 1, maxRank: 2, icon: 'spell_nature_ancestralguardian', spellId: 20500, ranks: [
        'The Berserker Rage ability will generate 5 rage when used.',
        'The Berserker Rage ability will generate 10 rage when used.',
      ] },
      { key: 'flurry', name: 'Flurry', tier: 6, col: 3, maxRank: 5, icon: 'ability_ghoulfrenzy', spellId: 12319, requires: { key: 'enrage', rank: 5 }, ranks: [
        'Increases your attack speed by 10% for your next 3 swings after dealing a melee critical strike.',
        'Increases your attack speed by 15% for your next 3 swings after dealing a melee critical strike.',
        'Increases your attack speed by 20% for your next 3 swings after dealing a melee critical strike.',
        'Increases your attack speed by 25% for your next 3 swings after dealing a melee critical strike.',
        'Increases your attack speed by 30% for your next 3 swings after dealing a melee critical strike.',
      ] },
      { key: 'bloodthirst', name: 'Bloodthirst', tier: 7, col: 2, maxRank: 1, icon: 'spell_nature_bloodlust', spellId: 23881, requires: { key: 'death-wish', rank: 1 }, ranks: [
        'Instantly attack the target causing damage equal to 45% of your attack power.  In addition, the next 5 successful melee attacks will restore 10 health.  This effect lasts 8 sec.',
      ] },
    ],
  },
  {
    key: 'protection',
    name: 'Protection',
    icon: 'inv_shield_06',
    talents: [
      { key: 'shield-specialization', name: 'Shield Specialization', tier: 1, col: 2, maxRank: 5, icon: 'inv_shield_06', spellId: 12298, ranks: [
        'Increases your chance to block attacks with a shield by 1% and has a 20% chance to generate 1 rage when a block occurs.',
        'Increases your chance to block attacks with a shield by 2% and has a 40% chance to generate 1 rage when a block occurs.',
        'Increases your chance to block attacks with a shield by 3% and has a 60% chance to generate 1 rage when a block occurs.',
        'Increases your chance to block attacks with a shield by 4% and has a 80% chance to generate 1 rage when a block occurs.',
        'Increases your chance to block attacks with a shield by 5% and has a 100% chance to generate 1 rage when a block occurs.',
      ] },
      { key: 'anticipation', name: 'Anticipation', tier: 1, col: 3, maxRank: 5, icon: 'spell_nature_mirrorimage', spellId: 12297, ranks: [
        'Increases your Defense skill by 2.',
        'Increases your Defense skill by 4.',
        'Increases your Defense skill by 6.',
        'Increases your Defense skill by 8.',
        'Increases your Defense skill by 10.',
      ] },
      { key: 'improved-bloodrage', name: 'Improved Bloodrage', tier: 2, col: 1, maxRank: 2, icon: 'ability_racial_bloodrage', spellId: 12301, ranks: [
        'Increases the instant Rage generated by your Bloodrage ability by 2.',
        'Increases the instant Rage generated by your Bloodrage ability by 5.',
      ] },
      { key: 'toughness', name: 'Toughness', tier: 2, col: 3, maxRank: 5, icon: 'spell_holy_devotion', spellId: 12299, ranks: [
        'Increases your armor value from items by 2%.',
        'Increases your armor value from items by 4%.',
        'Increases your armor value from items by 6%.',
        'Increases your armor value from items by 8%.',
        'Increases your armor value from items by 10%.',
      ] },
      { key: 'iron-will', name: 'Iron Will', tier: 2, col: 4, maxRank: 5, icon: 'spell_magic_magearmor', spellId: 12300, ranks: [
        'Increases your chance to resist Stun and Charm effects by an additional 3%.',
        'Increases your chance to resist Stun and Charm effects by an additional 6%.',
        'Increases your chance to resist Stun and Charm effects by an additional 9%.',
        'Increases your chance to resist Stun and Charm effects by an additional 12%.',
        'Increases your chance to resist Stun and Charm effects by an additional 15%.',
      ] },
      { key: 'last-stand', name: 'Last Stand', tier: 3, col: 1, maxRank: 1, icon: 'spell_holy_ashestoashes', spellId: 12975, requires: { key: 'improved-bloodrage', rank: 2 }, ranks: [
        'When activated, this ability temporarily grants you 30% of your maximum hit points for 20 seconds.  After the effect expires, the hit points are lost.',
      ] },
      { key: 'improved-shield-block', name: 'Improved Shield Block', tier: 3, col: 2, maxRank: 3, icon: 'ability_defend', spellId: 12945, requires: { key: 'shield-specialization', rank: 5 }, ranks: [
        'Allows your Shield Block ability to block an additional attack and increases the duration by 0.5 second.',
        'Allows your Shield Block ability to block an additional attack and increases the duration by 1 second.',
        'Allows your Shield Block ability to block an additional attack and increases the duration by 2 seconds.',
      ] },
      { key: 'improved-revenge', name: 'Improved Revenge', tier: 3, col: 3, maxRank: 3, icon: 'ability_warrior_revenge', spellId: 12797, ranks: [
        'Gives your Revenge ability a 15% chance to stun the target for 3 sec.',
        'Gives your Revenge ability a 30% chance to stun the target for 3 sec.',
        'Gives your Revenge ability a 45% chance to stun the target for 3 sec.',
      ] },
      { key: 'defiance', name: 'Defiance', tier: 3, col: 4, maxRank: 5, icon: 'ability_warrior_innerrage', spellId: 12303, ranks: [
        'Increases the threat generated by your attacks by 3% while in Defensive Stance.',
        'Increases the threat generated by your attacks by 6% while in Defensive Stance.',
        'Increases the threat generated by your attacks by 9% while in Defensive Stance.',
        'Increases the threat generated by your attacks by 12% while in Defensive Stance.',
        'Increases the threat generated by your attacks by 15% while in Defensive Stance.',
      ] },
      { key: 'improved-sunder-armor', name: 'Improved Sunder Armor', tier: 4, col: 1, maxRank: 3, icon: 'ability_warrior_sunder', spellId: 12308, ranks: [
        'Reduces the cost of your Sunder Armor ability by 1 rage point.',
        'Reduces the cost of your Sunder Armor ability by 2 rage points.',
        'Reduces the cost of your Sunder Armor ability by 3 rage points.',
      ] },
      { key: 'improved-disarm', name: 'Improved Disarm', tier: 4, col: 2, maxRank: 3, icon: 'ability_warrior_disarm', spellId: 12313, ranks: [
        'Increases the duration of your Disarm ability by 1 secs.',
        'Increases the duration of your Disarm ability by 2 secs.',
        'Increases the duration of your Disarm ability by 3 secs.',
      ] },
      { key: 'improved-taunt', name: 'Improved Taunt', tier: 4, col: 3, maxRank: 2, icon: 'spell_nature_reincarnation', spellId: 12302, ranks: [
        'Reduces the cooldown of your Taunt ability by 1 sec.',
        'Reduces the cooldown of your Taunt ability by 2 sec.',
      ] },
      { key: 'improved-shield-wall', name: 'Improved Shield Wall', tier: 5, col: 1, maxRank: 2, icon: 'ability_warrior_shieldwall', spellId: 12312, ranks: [
        'Increases the effect duration of your Shield Wall ability by 3 secs.',
        'Increases the effect duration of your Shield Wall ability by 5 secs.',
      ] },
      { key: 'concussion-blow', name: 'Concussion Blow', tier: 5, col: 2, maxRank: 1, icon: 'ability_thunderbolt', spellId: 12809, ranks: [
        'Stuns the opponent for 5 sec.',
      ] },
      { key: 'improved-shield-bash', name: 'Improved Shield Bash', tier: 5, col: 3, maxRank: 2, icon: 'ability_warrior_shieldbash', spellId: 12311, ranks: [
        'Gives your Shield Bash ability a 50% chance to silence the target for 3 sec.',
        'Gives your Shield Bash ability a 100% chance to silence the target for 3 sec.',
      ] },
      { key: 'one-handed-weapon-specialization', name: 'One-Handed Weapon Specialization', tier: 6, col: 3, maxRank: 5, icon: 'inv_sword_20', spellId: 16538, ranks: [
        'Increases the damage you deal with One-Handed Melee weapons by 2%.',
        'Increases the damage you deal with One-Handed Melee weapons by 4%.',
        'Increases the damage you deal with One-Handed Melee weapons by 6%.',
        'Increases the damage you deal with One-Handed Melee weapons by 8%.',
        'Increases the damage you deal with One-Handed Melee weapons by 10%.',
      ] },
      { key: 'shield-slam', name: 'Shield Slam', tier: 7, col: 2, maxRank: 1, icon: 'inv_shield_05', spellId: 23922, requires: { key: 'concussion-blow', rank: 1 }, ranks: [
        'Slam the target with your shield, causing 225 to 235 damage, modified by your shield block value, and has a 50% chance of dispelling 1 magic effect on the target.  Also causes a high amount of threat.',
      ] },
    ],
  },
];

const TALENT_MAX_POINTS = 51;
const TALENT_POINTS_PER_TIER = 5;
